let token=localStorage.getItem('floodai_token'), me=JSON.parse(localStorage.getItem('floodai_user')||'null'), mode='login', map, marker;
const $=id=>document.getElementById(id); const api=(url,opt={})=>fetch(url,{...opt,headers:{...(opt.headers||{}),...(token?{Authorization:`Bearer ${token}`}:{})}}).then(async r=>{const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||'Request failed');return d});
async function health(){try{const h=await api('/api/health');$('connection').innerHTML=`<span class="${h.database&&h.aiConfigured?'ok':'error'}">● Backend ${h.database?'Connected':'DB Offline'} · AI ${h.aiConfigured?'Ready':'API Key Missing'}</span>`}catch{$('connection').innerHTML='<span class="error">● Backend Offline</span>'}} health();
function showAuth(m){mode=m;$('name').hidden=m==='login';$('name').required=m==='register';$('authForm').querySelector('button').textContent=m==='login'?'Login':'Create Account'}
$('authForm').onsubmit=async e=>{e.preventDefault();try{const d=await api('/api/auth/'+(mode==='login'?'login':'register'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('name').value,email:$('email').value,password:$('password').value})});token=d.token;me=d.user;localStorage.setItem('floodai_token',token);localStorage.setItem('floodai_user',JSON.stringify(me));startApp()}catch(x){$('authMsg').textContent=x.message;$('authMsg').className='error'}};
function startApp(){ $('auth').hidden=true;$('app').hidden=false;$('welcome').textContent='Welcome, '+me.name;$('roleBadge').textContent=me.role.toUpperCase();$('adminView').hidden=me.role!=='admin';$('userView').hidden=me.role==='admin';if(me.role==='admin')loadAdmin();else{loadMine();loadMissingMine();initMap()}const s=io();s.on('emergency:new',()=>{if(me.role==='admin')loadAdmin();else loadMine()});s.on('emergency:update',()=>{if(me.role==='admin')loadAdmin();else loadMine()});s.on('missing:new',()=>{if(me.role==='admin')loadAdmin();else loadMissingMine()});}
function logout(){localStorage.clear();location.reload()}
function getLocation(target='user'){navigator.geolocation?.getCurrentPosition(p=>{if(target==='user'){$('lat').value=p.coords.latitude;$('lng').value=p.coords.longitude;setMap(p.coords.latitude,p.coords.longitude)}else{$('mlat').value=p.coords.latitude;$('mlng').value=p.coords.longitude}},()=>alert('Location permission denied'))}
function initMap(){map=L.map('map').setView([11.0168,76.9558],11);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map)}function setMap(lat,lng){if(!map)return;if(marker)marker.remove();marker=L.marker([lat,lng]).addTo(map).bindPopup('Your reported location').openPopup();map.setView([lat,lng],14)}
$('emergencyForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData();fd.append('message',$('message').value);fd.append('language',$('language').value);fd.append('lat',$('lat').value);fd.append('lng',$('lng').value);fd.append('address',$('address').value);if($('image').files[0])fd.append('image',$('image').files[0]);$('caseMsg').textContent='Sending to backend → Gemini AI → MongoDB...';try{const d=await api('/api/emergencies',{method:'POST',body:fd});$('caseMsg').textContent=`Saved. AI priority: ${d.ai.priority}. ${d.ai.summary}`;$('emergencyForm').reset();loadMine()}catch(x){$('caseMsg').textContent=x.message;$('caseMsg').className='error'}};
async function loadMine(){const a=await api('/api/emergencies/mine');$('myCases').innerHTML=a.length?a.map(caseHtml).join(''):'<p>No emergency reports yet.</p>'}function caseHtml(c){return `<div class="case priority-${c.ai?.priority||'Medium'}"><b>${c.ai?.emergencyType||'Emergency'}</b> <span class="pill">${c.ai?.priority||'Medium'}</span><span class="pill">${c.status}</span><p>${esc(c.ai?.summary||c.message)}</p><small>Need: ${esc(c.ai?.need||'Not specified')} · People: ${c.ai?.peopleCount??'—'}</small></div>`}
$('missingForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData();fd.append('name',$('mname').value);fd.append('age',$('mage').value);fd.append('description',$('mdesc').value);fd.append('address',$('maddress').value);fd.append('lat',$('mlat').value);fd.append('lng',$('mlng').value);if($('mphoto').files[0])fd.append('photo',$('mphoto').files[0]);try{await api('/api/missing',{method:'POST',body:fd});$('missingForm').reset();loadMissingMine()}catch(x){alert(x.message)}};
async function loadMissingMine(){const a=await api('/api/missing/mine');$('myMissing').innerHTML=a.map(m=>`<div class="case"><b>${esc(m.name)}</b> · ${m.status}<p>${esc(m.description||'')}</p></div>`).join('')||'<p>No missing-person reports.</p>'}
async function loadAdmin(){const [s,c,v,m]=await Promise.all([api('/api/dashboard'),api('/api/emergencies'),api('/api/volunteers'),api('/api/missing')]);$('stats').innerHTML=[['Total',s.total],['Critical',s.critical],['Active',s.active],['Resolved',s.resolved],['Missing',s.missing],['Available Teams',s.availableVolunteers]].map(x=>`<div class="stat"><b>${x[1]}</b>${x[0]}</div>`).join('');$('adminCases').innerHTML=c.map(x=>`<div class="case priority-${x.ai?.priority||'Medium'}"><b>${esc(x.ai?.emergencyType||'Emergency')}</b> <span class="pill">${x.ai?.priority}</span> <span class="pill">${x.status}</span><p>${esc(x.ai?.summary||x.message)}</p><small>${x.user?.name||''} · ${x.location?.address||'Location shared'}</small><div><select onchange="setStatus('${x._id}',this.value)"><option>Update status</option>${['Pending','Verified','Assigned','Rescue In Progress','Resolved'].map(z=>`<option ${z===x.status?'selected':''}>${z}</option>`).join('')}</select></div></div>`).join('')||'<p>No cases yet.</p>';$('volunteers').innerHTML=v.map(x=>`<div class="case"><b>${esc(x.name)}</b> · ${esc(x.team||'')} · ${x.available?'Available':'Busy'}<br><small>${esc((x.skills||[]).join(', '))}</small></div>`).join('')||'<p>No volunteers.</p>';$('adminMissing').innerHTML=m.map(x=>`<div class="case"><b>${esc(x.name)}</b> · ${x.status}<select onchange="setMissing('${x._id}',this.value)"><option>Change status</option>${['Missing','Possible Match','Found','Verified'].map(z=>`<option>${z}</option>`).join('')}</select></div>`).join('')||'<p>No reports.</p>'}
async function setStatus(id,status){if(status==='Update status')return;await api('/api/emergencies/'+id+'/status',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});loadAdmin()}async function setMissing(id,status){if(status==='Change status')return;await api('/api/missing/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});loadAdmin()}
$('volForm').onsubmit=async e=>{e.preventDefault();await api('/api/volunteers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('vname').value,phone:$('vphone').value,team:$('vteam').value,skills:$('vskills').value.split(',').map(x=>x.trim()).filter(Boolean)})});$('volForm').reset();loadAdmin()};
function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}if(token&&me)startApp();
